### ISSUE TITLE
Cannot add favourites in settings page and Icon pack support

### ISSUE THREAD

**Issue by Ubee2268** [mslalith/focus_launcher#101]
I have noticed that I cannot add favourites from the settings page, it's not working. However, i am able to clear the favourites. Also, could you please try to add the icon pack support. Thanks!

**Comment by mslalith** [comment]
fixed in #114. I created #115 to track Icon Support support. Closing this

**Comment by mslalith** [comment]
Fixed in v0.4.0 release

**Comment by mslalith** [comment]
@Ubee2268 Icon Pack support added in [v0.5.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.5.0). Do try out

**Comment by Ubee2268** [comment]
thanks a lot 😊
Downloaded the latest version...
