### ISSUE TITLE
Bug: app is missing from list

### ISSUE THREAD

**Issue by v0iden** [mslalith/focus_launcher#211]
As far as I can tell, one of my apps is missing from the list. it's not hidden. it's this app: https://play.google.com/store/apps/details?id=co.timesquared.timetracker. 

sorry if I've missed something, but I see no reason why this app would be missing from the list. I am running the latest version from Google play. just started using the app. 

update: found out there was a newer version on f-droid, updated, but the problem persists.

**Comment by mslalith** [comment]
Fixed in [v0.7.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.7.0)
