### ISSUE TITLE
issue: bad contrast with favourites

### ISSUE THREAD

**Issue by v0iden** [mslalith/focus_launcher#216]
the text for the [obsidian.md](https://play.google.com/store/apps/details?id=md.obsidian)  app is really hard to read in light mode. a fix would be appreciated.
![Screenshot_20230518-204737](https://github.com/mslalith/focus_launcher/assets/31285047/4ba94089-2f24-4c78-af15-4474c5b38cd0)

**Comment by mslalith** [comment]
Fixed in [v0.7.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.7.0)
