### ISSUE TITLE
Feature: Use the similar text-only icons from favorites in app drawer

### ISSUE THREAD

**Issue by Akselmo** [mslalith/focus_launcher#217]
I really like how the icons in the favorites the icons turn into just blocks with text inside of them. 

What I'd like to see is also have the same functionality in the app drawer in a list. So instead of apps with their icons, it would be list of similar blocks with text. I think icons can be distracting so this would make it more clear for me what I'm looking for. :)

**Comment by v0iden** [comment]
in the settings, you can choose the app drawer to be in a list without icons. still not the same, obviously, but better.

**Comment by Akselmo** [comment]
Yeah I tried that! While great, I do like the colored "blocks" more because colors can help with spotting the right application from the list. When seeing the right color one can then start focusing more on reading is it the right app.

Besides I just think it looks nice haha, but maybe that's just me.

**Comment by v0iden** [comment]
in my case, I want my phone to be less addictive. therefore I want a simple list of apps that aren't that easily recognizable. it sounds like you're more interested in aesthetics, no? two different use cases, not sure which one the app is intended for.

**Comment by v0iden** [comment]
in my case, I want my phone to be less addictive. therefore I want a simple list of apps that aren't that easily recognizable. it sounds like you're more interested in aesthetics, no? two different use cases, not sure which one the app is intended for.

**Comment by Akselmo** [comment]
Not *just* aesthetics (it can be a bonus).

Colors can help distinct things and grasp quicker what the item is.

For example lets say your phone app is always green. This way you know every time to scroll down the list of items to P, and if it has multiple items, you have associated green with phone. So you can look only at the green items.

Then from those green items you can pick the one you need, which is the one you need.

It reduces cognitive load, basically. Kind of like when programming and having consistent syntax highlighting: You pretty much always can rely that, for example string type elements are green ones.

**Comment by mslalith** [comment]
Good idea. I can provide an option under App Drawer Setting for the user to choose either Icons or Coloured Blocks. But first I have to figure out https://github.com/mslalith/focus_launcher/issues/216 😉

**Comment by mslalith** [comment]
Available in [v0.7.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.7.0)
