### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by tdpo2** [mslalith/focus_launcher#240]
1. Be able to choose color for each favorite app.
2. Be able to change name for each favorite(still have original name in drawer).
3. Change favorite alignment(like for the clock, left, center, right).
4. Run app when clicking on the clock(alarm app).
5. More flexibility changing favorite app order and sizing(how much blank space for each favorite).
6. When you reorder favorites in preview mode you get two favorites in one line but at the end there is three favorites.

**Comment by tdpo2** [comment]
Be able to hide favorite app.

**Comment by mslalith** [comment]
> 1. Be able to choose color for each favorite app.
> 2. Be able to change name for each favorite(still have original name in drawer).

Above I'm not planning to add as of now. Depending on the requests I'll plan in future releases.

> 3. Change favorite alignment(like for the clock, left, center, right).
> 4. Run app when clicking on the clock(alarm app).

Available in [v0.7.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.7.0)

> 5. More flexibility changing favorite app order and sizing(how much blank space for each favorite).

I'm planning to add drag and drop support to reorder favorites. Keep an eye out for this.

> 6. When you reorder favorites in preview mode you get two favorites in one line but at the end there is three favorites.

Can you explain a bit more on this?

**Comment by tdpo2** [comment]
> > 6. When you reorder favorites in preview mode you get two favorites in one line but at the end there is three favorites.
> 
> Can you explain a bit more on this?

When you open reorder window it is not the same size as plain. Size shrinks because of the borders and preview to actual placement after you complete reorder is not 1:1.

**Comment by mslalith** [comment]
Right, that is because favorites adopt to the size they have. When the size is changed, they are resizing themselves to the new size.

**Comment by tdpo2** [comment]
What I meant:


(no names due to privacy).
![FOCUS](https://github.com/mslalith/focus_launcher/assets/67642658/4764bbf1-eba0-4584-9fd5-ea5e16908263)

**Comment by tdpo2** [comment]
> What I meant:
> 
> (no names due to privacy). ![FOCUS](https://user-images.githubusercontent.com/67642658/250171793-4764bbf1-eba0-4584-9fd5-ea5e16908263.png)

This time amount of apps is the same. But sometimes number of apps per line changes due to name size so you could have two halves at the bottom or just one like now. It depends how you reorder them and what kind of name do they have.

**Comment by mslalith** [comment]
I understand. As I mentioned earlier, when you are trying to rearrange the size for favorites is reduce to make room for the border. With the available space the favorites are rearranging themselves.
I can take this as an improvement in the future releases

**Comment by mslalith** [comment]
@tdpo2 Drag n drop feature has been added to Favorites in [v0.9.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.9.0). Do checkout

**Comment by mslalith** [comment]
> 6. When you reorder favorites in preview mode you get two favorites in one line but at the end there is three favorites.

The UI for Favorites is changed, so this should not occur
