### ISSUE TITLE
It should clear the input array when we swipe right and are looking for apps, once you open the app the search bar should be clear so that you don't have to manually erase it and just better UI experience 

### ISSUE THREAD

**Issue by MostlyKIGuess** [mslalith/focus_launcher#258]

**Comment by MostlyKIGuess** [comment]
I want to work on this issue , 

I think the function is already there in https://github.com/mslalith/focus_launcher/blob/main/core/ui/src/main/kotlin/dev/mslalith/focuslauncher/core/ui/SearchField.kt

  trailingIcon = {
            AnimatedVisibility(visible = query.isNotEmpty()) {
                Box(
                    modifier = Modifier
                        .clip(shape = CircleShape)
                        .clickable { onQueryChange("") }
                        .padding(all = 4.dp)
                ) {
                    Icon(
                        painter = painterResource(id = R.drawable.ic_close),
                        contentDescription = stringResource(id = R.string.clear)
                    )
                    
                    but it's not emptying the string on query, can anyone guide me through it?

**Comment by mslalith** [comment]
Hey @MostlyKIGuess, you can clear the query by setting it to empty before launching the app

https://github.com/mslalith/focus_launcher/blob/134425a07c5e2687b3c32a6e835feaf1a5694815/feature/appdrawerpage/src/main/kotlin/dev/mslalith/focuslauncher/feature/appdrawerpage/AppDrawerPage.kt#L75-L78

**Comment by supermar1010** [comment]
I'd also like this feature. I tried to have a go but I'm not really good with jetpack-compose. 

Reseeting when opening the app works like this:
```
appDrawerPageViewModel.searchAppQuery("")
```
But what I failed at achieving was, to empty the searchfield everytime you navigate away (e.g. by going to the homescreen)

**Comment by mslalith** [comment]
@supermar1010 thanks for the PR. As for the other scenario, below is where we hide the keyboard on navigating away. You can reset here
https://github.com/mslalith/focus_launcher/blob/134425a07c5e2687b3c32a6e835feaf1a5694815/feature/appdrawerpage/src/main/kotlin/dev/mslalith/focuslauncher/feature/appdrawerpage/AppDrawerPage.kt#L55-L57

I'm planning on refactoring to stateless & stateful Composables. I would take care of this as part of refactoring

**Comment by mslalith** [comment]
Fixed in https://github.com/mslalith/focus_launcher/pull/311/commits/9138520350b210c15d95a01b02b6a220ec4ce461

**Comment by MostlyKIGuess** [comment]
oh cool, thanks, sorry I didn't update!

**Comment by mslalith** [comment]
Fixed in [v0.8.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.8.0)
