### ISSUE TITLE
android.permission.REQUEST_DELETE_PACKAGES

### ISSUE THREAD

**Issue by IzzySoft** [mslalith/focus_launcher#379]
Just wondering why the launcher requests `android.permission.REQUEST_DELETE_PACKAGES`? The app description does not tell. Could you please clarify? Thanks in advance!

**Comment by IzzySoft** [comment]
I suspected that but wasn't sure. Of course makes sense for the app drawer part. Thanks for confirming! Added it to the "allow-list".

Btw: [Trustlook is unhappy](https://www.virustotal.com/gui/file/d2e849291829faa88cbea6d9912aa2193662c9ea382a74928d84683347806201/detection/f-d2e849291829faa88cbea6d9912aa2193662c9ea382a74928d84683347806201-1707676230). Should someone ask: most likely a false positive (just 1 out of 64 :man_shrugging:)

**Comment by IzzySoft** [comment]
PS: Just in case you're unaware, please [see here](https://apt.izzysoft.de/packages/dev.mslalith.focuslauncher/) – and if you like what you see, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to make that PlayStore one look less lonely :smile:

**Comment by mslalith** [comment]
> [Trustlook is unhappy](https://www.virustotal.com/gui/file/d2e849291829faa88cbea6d9912aa2193662c9ea382a74928d84683347806201/detection/f-d2e849291829faa88cbea6d9912aa2193662c9ea382a74928d84683347806201-1707676230). Should someone ask: most likely a false positive (just 1 out of 64 🤷‍♂️)

I reanalysed. It's clean now 😉

Added IzzyOnDroid badge. Checkout [here](https://github.com/mslalith/focus_launcher/tree/develop?tab=readme-ov-file#focus-launcher)

**Comment by IzzySoft** [comment]
Yeeeha! Thanks – and congrats (not necessarily in this order :partying_face:)!
