### ISSUE TITLE
Request: Change Background image

### ISSUE THREAD

**Issue by heubergen** [mslalith/focus_launcher#69]
I'd love to change/set the background image.

**Comment by mslalith** [comment]
Thank you for your interest in this app.

The background colour of favourites currently changes depending on the app's icon. My worry is that if background image support is offered, favourites may appear odd or maybe not be viewable on some images. The capability to change background images, though, appeals to me. I'll leave it open for now. I'll consider granting it if there are several requests.

**Comment by mslalith** [comment]
@heubergen Changing background will not be supported, as this will conflict with favorites color. i'll be revisiting this if there are any changes to favorites. Closing this for now
