### ISSUE TITLE
remove proprietary components and promotion of proprietary services

### ISSUE THREAD

**Issue by Wjxfi** [mslalith/focus_launcher#70]
This was reported in izzyondroid

**Comment by mslalith** [comment]
I was considering it! (https://github.com/mslalith/focus_launcher/issues/11#issuecomment-1434120347)

**Comment by mslalith** [comment]
Fixed in #73

**Comment by IzzySoft** [comment]
Thanks! Can you please send me a reminder to cross-check once the next release was made, so I can remove the "anti-features" from the [listing in my repo](https://apt.izzysoft.de/fdroid/index/apk/dev.mslalith.focuslauncher)?

Oh, PS: If you wish, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

**Comment by mslalith** [comment]
@IzzySoft [v0.3.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.3.0) is out

**Comment by IzzySoft** [comment]
Pulled, checked, confirmed – AntiFeatures removed. Thanks!
