### ISSUE TITLE
support for app copies. (miui)

### ISSUE THREAD

**Issue by Wjxfi** [mslalith/focus_launcher#71]
This is only available on xiaomi. This is very convenient. I want to switch to your launcher but I can't because of the lack of copy support

https://youtu.be/udBAcKXLkIU?t=52

**Comment by mslalith** [comment]
I don't understand the need of cloning a Launcher. But if you want to have two launchers of same app, I believe there are some 3rd party apps which can help you.

Closing this for now as this use case is limited
