### ISSUE TITLE
Clock gets cut off when status bar is enabled. 

### ISSUE THREAD

**Issue by caemputer** [mslalith/focus_launcher#90]
When enabling the status bar the clock gets cut off. What's weird about this is that when the status bar is disabled the clock moves down so that it would not have been cut off. When using the 'Enable Clock 24' feature the clock disappears entirely. Both return to the normal position after a while but this is not reliable. This was experienced on the latest f-droid release.

**Comment by mslalith** [comment]
Hi @c4em, I didn't see this issue in my testing. I just released v0.5.1 which has couple of status bar changes. Do test with the latest version. If you still see the issue, please add your device n OS details. In addition, recording would also help
